const express=require("express");
const authMiddleware=require("../middleware/authMiddle");
const adminMiddleware=require("../middleware/adminMiddleware");
const {loginUser} =require("../controllers/authcontrol");
const { createQuestion, readQuestion,updateQues,deleteQues } = require("../controllers/createQuestion");
const router=express.Router();
router.post("/login",loginUser);
router.post("/questions",authMiddleware,adminMiddleware,createQuestion);
router.get("/questions/:id",authMiddleware,readQuestion);
router.put("/questions/:id",authMiddleware,adminMiddleware,updateQues);
router.delete("/questions/:id",authMiddleware,adminMiddleware,deleteQues);
module.exports=router;